global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "service-one"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "service-two"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: ["host.docker.internal:8083"]