spring:
  application:
    name: springboot-multi-module

  datasource:
    url: jdbc:postgresql://localhost:5455/micro-post
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

    # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false