version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: social-media-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social-media-postgres
    ports:
      - "5456:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: social-media-mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: social-media-mongo
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
