spring:
  application:
    name: service-one

server:
  port: 8082

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus

  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true

